# Generated by Django 4.1 on 2022-08-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('meal', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default='B', max_length=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(verbose_name='Stock Date'),
        ),
    ]
