# Generated by Django 4.1 on 2022-08-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_dish_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sauce',
            name='dishes',
            field=models.ManyToManyField(to='main_app.dish'),
        ),
    ]
